apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
namespace: winvestco

resources:
  - ../../base

replicas:
  - name: eureka-server
    count: 3
  - name: api-gateway
    count: 3
  - name: user-service
    count: 3
  - name: market-service
    count: 3
  - name: portfolio-service
    count: 3
  - name: funds-service
    count: 3
  - name: ledger-service
    count: 3
  - name: order-service
    count: 3
  - name: trade-service
    count: 3
  - name: notification-service
    count: 3
  - name: payment-service
    count: 3
  - name: report-service
    count: 2
  - name: risk-service
    count: 3
  - name: schedule-service
    count: 2
  - name: frontend
    count: 3

images:
  - name: ${DOCKERHUB_NAMESPACE}/eureka-server
    newTag: latest
  - name: ${DOCKERHUB_NAMESPACE}/api-gateway
    newTag: latest
  - name: ${DOCKERHUB_NAMESPACE}/user-service
    newTag: latest
  - name: ${DOCKERHUB_NAMESPACE}/market-service
    newTag: latest
  - name: ${DOCKERHUB_NAMESPACE}/portfolio-service
    newTag: latest
  - name: ${DOCKERHUB_NAMESPACE}/funds-service
    newTag: latest
  - name: ${DOCKERHUB_NAMESPACE}/ledger-service
    newTag: latest
  - name: ${DOCKERHUB_NAMESPACE}/order-service
    newTag: latest
  - name: ${DOCKERHUB_NAMESPACE}/trade-service
    newTag: latest
  - name: ${DOCKERHUB_NAMESPACE}/notification-service
    newTag: latest
  - name: ${DOCKERHUB_NAMESPACE}/payment-service
    newTag: latest
  - name: ${DOCKERHUB_NAMESPACE}/report-service
    newTag: latest
  - name: ${DOCKERHUB_NAMESPACE}/risk-service
    newTag: latest
  - name: ${DOCKERHUB_NAMESPACE}/schedule-service
    newTag: latest
  - name: ${DOCKERHUB_NAMESPACE}/frontend
    newTag: latest

patchesStrategicMerge:
  - config-patch.yaml
  - resource-patch.yaml
