apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: winvestco
data:
  POSTGRES_USER: "winvestco"
  POSTGRES_DB: "winvestco"
  POSTGRES_MULTIPLE_DATABASES: "user_service,market_service,portfolio_service,funds_service,ledger_service,order_service,trade_service,notification_service,payment_service,report_service,risk_service,schedule_service"
  PGDATA: "/var/lib/postgresql/data/pgdata"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: winvestco
data:
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: winvestco
data:
  RABBITMQ_DEFAULT_USER: "winvestco"
  RABBITMQ_DEFAULT_VHOST: "/"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: winvestco
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: winvestco
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  SPRING_PROFILES_ACTIVE: "prod"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "redis"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_MANAGEMENT_PORT: "15672"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318/v1/traces"
  OTEL_TRACES_SAMPLER: "parentbased_traceidratio"
  OTEL_TRACES_SAMPLER_ARG: "1.0"
