apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: winvestco
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets: []

    rule_files:

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'eureka-server'
        static_configs:
          - targets: ['eureka-server:8761']
        metrics_path: '/actuator/prometheus'

      - job_name: 'api-gateway'
        static_configs:
          - targets: ['api-gateway:8090']
        metrics_path: '/actuator/prometheus'

      - job_name: 'user-service'
        static_configs:
          - targets: ['user-service:8088']
        metrics_path: '/actuator/prometheus'

      - job_name: 'market-service'
        static_configs:
          - targets: ['market-service:8084']
        metrics_path: '/actuator/prometheus'

      - job_name: 'portfolio-service'
        static_configs:
          - targets: ['portfolio-service:8086']
        metrics_path: '/actuator/prometheus'

      - job_name: 'funds-service'
        static_configs:
          - targets: ['funds-service:8085']
        metrics_path: '/actuator/prometheus'

      - job_name: 'ledger-service'
        static_configs:
          - targets: ['ledger-service:8082']
        metrics_path: '/actuator/prometheus'

      - job_name: 'order-service'
        static_configs:
          - targets: ['order-service:8081']
        metrics_path: '/actuator/prometheus'

      - job_name: 'trade-service'
        static_configs:
          - targets: ['trade-service:8083']
        metrics_path: '/actuator/prometheus'

      - job_name: 'notification-service'
        static_configs:
          - targets: ['notification-service:8089']
        metrics_path: '/actuator/prometheus'

      - job_name: 'payment-service'
        static_configs:
          - targets: ['payment-service:8087']
        metrics_path: '/actuator/prometheus'

      - job_name: 'report-service'
        static_configs:
          - targets: ['report-service:8091']
        metrics_path: '/actuator/prometheus'

      - job_name: 'risk-service'
        static_configs:
          - targets: ['risk-service:8092']
        metrics_path: '/actuator/prometheus'

      - job_name: 'schedule-service'
        static_configs:
          - targets: ['schedule-service:8095']
        metrics_path: '/actuator/prometheus'
